### ISSUE TITLE
初いいねの時に本を登録する

### ISSUE THREAD

**Issue by funator26** [mickeyjoe666/OnBoardingSupportSystem#28]
期待される動作：
　「いいね」ボタンを押した時に、データベースにその本の情報が登録されていなければまず本の情報を登録してから
　「いいね」を追加する

**Comment by funator26** [comment]
実装案
1. （フロント）likeを押した時に本の情報を持たせてリクエストを送る
2. （サーバ）受け取ったリクエストから、その本の情報があるかどうか確認する
  2.1 ある場合：普通にいいねを追加する
  2.2 ない場合：本を登録してからいいねを追加する

**Comment by mickeyjoe666** [comment]
対応済のでclose
